const USERDATA = [
  {
    _id: '659dba21dee13b881defde73',
    name: 'Niraj Jadhav',
    age: 34,
    gender: 'Male',
    race: 'Asian',
    height: 165,
    weight: 65,
    BMI: 23.87,
    bloodGroup: 'A+',
    email: 'Niraj123@example.com',
    password: '$2b$10$KzECfRZoqpPW/fD1d2syQOQFK6Ey9OiV8PwtL42WgQI/r0Gq9cACm',
    nurse: '659cf772bc7d700486f36a4e',
    comorbidities: {
      diabetes: true,
      HTN: false,
      asthma: true,
      smoking: false,
      alcoholUse: true,
      kidneyDisease: false,
      pastMI: true,
      pastCVA: false,
      priorStenting: true,
      priorCABG: false,
    },
    medicationHistory: {diuretics: false},
    visit: [],
    __v: 0,
  },
  {
    _id: '659dbc76718cf4d3a3affd6c',
    name: 'Omkar Patil',
    age: 34,
    gender: 'Male',
    race: 'Asian',
    height: 165,
    weight: 65,
    BMI: 23.87,
    bloodGroup: 'A+',
    email: 'OmkarPatil@example.com',
    password: '$2b$10$RUTA7BKzDhEZh3KBF5pFHONVrQ77bD2YC1Fn0JYE5lI/rXKslO/Zi',
    nurse: '659cf772bc7d700486f36a4e',
    comorbidities: {
      diabetes: true,
      HTN: false,
      asthma: true,
      smoking: false,
      alcoholUse: true,
      kidneyDisease: false,
      pastMI: true,
      pastCVA: false,
      priorStenting: true,
      priorCABG: false,
    },
    medicationHistory: {diuretics: false},
    visit: [],
    __v: 0,
  },
  {
    _id: '659dbcf1718cf4d3a3affd76',
    name: 'Prabhu Gowda',
    age: 45,
    gender: 'Male',
    race: 'Asian',
    height: 165,
    weight: 65,
    BMI: 23.87,
    bloodGroup: 'A+',
    email: 'PrabhuGowda@example.com',
    password: '$2b$10$ECHucehz4CBA35OWNTZ8Uu7DmCyENoIX7XxljPFgbc.bwIFJrqWqq',
    nurse: '659cf772bc7d700486f36a4e',
    comorbidities: {
      diabetes: true,
      HTN: false,
      asthma: true,
      smoking: false,
      alcoholUse: true,
      kidneyDisease: false,
      pastMI: true,
      pastCVA: false,
      priorStenting: true,
      priorCABG: false,
    },
    medicationHistory: {diuretics: false},
    visit: [],
    __v: 0,
  },
];

export default USERDATA;
